service: aws-node-express-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  environment: ${file(env.json)}

functions:
  api:
    handler: sls.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-offline
