service: surebank-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  environment: ${file(env.json)}

functions:
  api:
    handler: sls.handler
    events:
      - httpApi:
          path: /{proxy+}
          method: ANY
          cors: true  # Enable CORS for this endpoint

plugins:
  - serverless-offline