const ACL_USER_CREATE = 'CREATE USER';
const ACL_USER_DELETE = 'DELETE USER';
const ACL_ROLE_CREATE = 'ALLOCATE ROLES';
const ACL_ROLE_UPDATE = 'UPDATE ROLE';

// Package Permissions
const ACL_PACKAGE_CREATE = 'CREATE_PACKAGE';
const ACL_PACKAGE_VIEW = 'VIEW_PACKAGE';
const ACL_PACKAGE_CONTRIBUTE = 'CONTRIBUTE_TO_PACKAGE';
const ACL_PACKAGE_WITHDRAW = 'WITHDRAW_FROM_PACKAGE';
const ACL_INTEREST_PACKAGE_CREATE = 'INTEREST_PACKAGE_CREATE';
const ACL_INTEREST_PACKAGE_VIEW = 'INTEREST_PACKAGE_VIEW';

// Payment Permissions
const ACL_PAYMENT_INITIATE = 'PAYMENT_INITIATE';
const ACL_PAYMENT_VERIFY = 'PAYMENT_VERIFY';
const ACL_VIRTUAL_ACCOUNT_VIEW = 'VIRTUAL_ACCOUNT_VIEW';

// Product Permissions
const ACL_PRODUCT_VIEW = 'PRODUCT_VIEW';
const ACL_PRODUCT_PURCHASE = 'PRODUCT_PURCHASE';
const ACL_CART_MANAGE = 'CART_MANAGE';

const PERMISSIONS = [
  {
    id: 1,
    name: ACL_USER_CREATE,
  },
  {
    id: 2,
    name: ACL_USER_DELETE,
  },
  {
    id: 3,
    name: ACL_ROLE_CREATE,
  },
  {
    id: 4,
    name: ACL_ROLE_UPDATE,
  },
  {
    id: 5,
    name: ACL_PACKAGE_CREATE,
  },
  {
    id: 6,
    name: ACL_PACKAGE_VIEW,
  },
  {
    id: 7,
    name: ACL_PACKAGE_CONTRIBUTE,
  },
  {
    id: 8,
    name: ACL_PACKAGE_WITHDRAW,
  },
  {
    id: 9,
    name: ACL_INTEREST_PACKAGE_CREATE,
  },
  {
    id: 10,
    name: ACL_INTEREST_PACKAGE_VIEW,
  },
  {
    id: 11,
    name: ACL_PAYMENT_INITIATE,
  },
  {
    id: 12,
    name: ACL_PAYMENT_VERIFY,
  },
  {
    id: 13,
    name: ACL_VIRTUAL_ACCOUNT_VIEW,
  },
  {
    id: 14,
    name: ACL_PRODUCT_VIEW,
  },
  {
    id: 15,
    name: ACL_PRODUCT_PURCHASE,
  },
  {
    id: 16,
    name: ACL_CART_MANAGE,
  },
];

module.exports = {
  PERMISSIONS,
  ACL_USER_CREATE,
  ACL_USER_DELETE,
  ACL_ROLE_CREATE,
  ACL_ROLE_UPDATE,
  ACL_PACKAGE_CREATE,
  ACL_PACKAGE_VIEW,
  ACL_PACKAGE_CONTRIBUTE,
  ACL_PACKAGE_WITHDRAW,
  ACL_INTEREST_PACKAGE_CREATE,
  ACL_INTEREST_PACKAGE_VIEW,
  ACL_PAYMENT_INITIATE,
  ACL_PAYMENT_VERIFY,
  ACL_VIRTUAL_ACCOUNT_VIEW,
  ACL_PRODUCT_VIEW,
  ACL_PRODUCT_PURCHASE,
  ACL_CART_MANAGE,
};
